<a href="https://colab.research.google.com/github/abdinegara783/ISFEST2023/blob/main/FEATURE_ENGINERING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#mengimport Library yang di butuhkan
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [12]:
#membaca Dataset
df=pd.read_csv('/content/DATA_PREPARATION.csv')
df.head(5)

,url,price_in_rp,title,address,district,city,lat,long,facilities,bedrooms,...,building_size_m2,carports,certificate,electricity,maid_bedrooms,maid_bathrooms,floors,property_condition,garages,furnishing
0,https://www.rumah123.com/properti/bekasi/hos11...,2.990000e+09,Rumah cantik Sumarecon Bekasi\nLingkungan asri...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"Tempat Jemuran, Jalur Telepon, Taman, Taman",4.0,...,272.0,0,shm - sertifikat hak milik,4400 mah,0,1,2.0,bagus,0,unfurnished
1,https://www.rumah123.com/properti/bekasi/hos10...,1.270000e+09,"Rumah Kekinian, Magenta Summarecon Bekasi","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,Taman,3.0,...,69.0,1,hgb - hak guna bangunan,2200 mah,0,0,2.0,bagus,0,Tidak diketahui
2,https://www.rumah123.com/properti/bekasi/hos10...,1.950000e+09,Rumah Cantik 2 Lantai Cluster Bluebell Summare...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"Jogging Track, Kolam Renang, Masjid, Taman,...",3.0,...,131.0,1,hgb - hak guna bangunan,2200 mah,1,1,2.0,bagus,1,unfurnished
3,https://www.rumah123.com/properti/bekasi/hos10...,3.300000e+09,Rumah Mewah 2Lantai L10x18 C di Cluster VERNON...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"Jalur Telepon, Jogging Track, Track Lari, K...",3.0,...,174.0,0,shm - sertifikat hak milik,3500 mah,1,1,2.0,bagus sekali,2,unfurnished
4,https://www.rumah123.com/properti/bekasi/hos10...,4.500000e+09,"Rumah Hoek di Cluster Maple Summarecon Bekasi,...","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,"Jogging Track, Kolam Renang, Taman, Jalur Te...",4.0,...,196.0,2,shm - sertifikat hak milik,3500 mah,1,1,2.0,bagus,1,unfurnished

In [13]:
df_baru = df.copy()

In [14]:
# Mencari kolom dengan tipe data non-numerik
kolom_nonnumerik = df_baru.select_dtypes(exclude=['number']).columns
df_nonnumerik = df_baru[kolom_nonnumerik]
df_nonnumerik.head(5)

,url,title,address,district,city,facilities,certificate,electricity,property_condition,furnishing
0,https://www.rumah123.com/properti/bekasi/hos11...,Rumah cantik Sumarecon Bekasi\nLingkungan asri...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,"Tempat Jemuran, Jalur Telepon, Taman, Taman",shm - sertifikat hak milik,4400 mah,bagus,unfurnished
1,https://www.rumah123.com/properti/bekasi/hos10...,"Rumah Kekinian, Magenta Summarecon Bekasi","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,Taman,hgb - hak guna bangunan,2200 mah,bagus,Tidak diketahui
2,https://www.rumah123.com/properti/bekasi/hos10...,Rumah Cantik 2 Lantai Cluster Bluebell Summare...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,"Jogging Track, Kolam Renang, Masjid, Taman,...",hgb - hak guna bangunan,2200 mah,bagus,unfurnished
3,https://www.rumah123.com/properti/bekasi/hos10...,Rumah Mewah 2Lantai L10x18 C di Cluster VERNON...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,"Jalur Telepon, Jogging Track, Track Lari, K...",shm - sertifikat hak milik,3500 mah,bagus sekali,unfurnished
4,https://www.rumah123.com/properti/bekasi/hos10...,"Rumah Hoek di Cluster Maple Summarecon Bekasi,...","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,"Jogging Track, Kolam Renang, Taman, Jalur Te...",shm - sertifikat hak milik,3500 mah,bagus,unfurnished

In [15]:
df_fasil = df_baru[['price_in_rp','facilities']]

In [16]:
def extract_facilities(df_fasil, col_name):
    facilities_list = df[col_name].str.split(', ').explode().unique().tolist()
    return facilities_list
facilities_list = extract_facilities(df_nonnumerik,'facilities')

In [17]:
def count_facilities(df, col_name):
    df['num_facilities'] = df[col_name].str.count(',') + 1
    return df
count_facilities(df_fasil, 'facilities')

<ipython-input-17-f375b0539056>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_facilities'] = df[col_name].str.count(',') + 1

,price_in_rp,facilities,num_facilities
0,2.990000e+09,"Tempat Jemuran, Jalur Telepon, Taman, Taman",4
1,1.270000e+09,Taman,1
2,1.950000e+09,"Jogging Track, Kolam Renang, Masjid, Taman,...",6
3,3.300000e+09,"Jalur Telepon, Jogging Track, Track Lari, K...",10
4,4.500000e+09,"Jogging Track, Kolam Renang, Taman, Jalur Te...",5
...,...,...,...
3548,5.880000e+08,"Masjid, Taman, Tempat Jemuran, Keamanan 24 ja...",10
3549,7.850000e+08,"Masjid, Keamanan, Jogging Track, Taman, Tem...",11
3550,7.550000e+08,"Keamanan, Taman, Jogging Track, Tempat Jemur...",7
3551,8.000000e+08,"Tempat Jemuran, Keamanan, Keamanan 24 jam, Was...",6
3552,6.550000e+08,"Kulkas, Masjid, Taman, Lapangan Bola, Tempat ...",15

In [18]:
def encode_facilities(df_fasil, col_name):
    encoded_df = df_fasil[col_name].str.get_dummies(sep=', ')
    return pd.concat([df_fasil, encoded_df], axis=1)
df_fasil = encode_facilities(df_fasil, 'facilities')

In [44]:
df_fasil

,price_in_rp,facilities,num_facilities,1 unit AC,AC,AC 3 unit,Ac,Akses Parkir,Balkon,Basement,...,carport,keamanan 24 jam,kitchen set (opsional),one gate sistem,one gate system,security 24jam,securty 24 jam,smart lock door,toren 500 liter,torrent
0,2.990000e+09,"Tempat Jemuran, Jalur Telepon, Taman, Taman",4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.270000e+09,Taman,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.950000e+09,"Jogging Track, Kolam Renang, Masjid, Taman,...",6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3.300000e+09,"Jalur Telepon, Jogging Track, Track Lari, K...",10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.500000e+09,"Jogging Track, Kolam Renang, Taman, Jalur Te...",5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,5.880000e+08,"Masjid, Taman, Tempat Jemuran, Keamanan 24 ja...",10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3549,7.850000e+08,"Masjid, Keamanan, Jogging Track, Taman, Tem...",11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3550,7.550000e+08,"Keamanan, Taman, Jogging Track, Tempat Jemur...",7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3551,8.000000e+08,"Tempat Jemuran, Keamanan, Keamanan 24 jam, Was...",6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3552,6.550000e+08,"Kulkas, Masjid, Taman, Lapangan Bola, Tempat ...",15,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

#**ENCODING NONNUMERIK VALUE**

In [38]:
df_nonum = df_nonnumerik[['electricity','property_condition','certificate','furnishing']]
df_nonum.head(10)

  electricity property_condition                 certificate       furnishing
0    4400 mah              bagus  shm - sertifikat hak milik      unfurnished
1    2200 mah              bagus     hgb - hak guna bangunan  Tidak diketahui
2    2200 mah              bagus     hgb - hak guna bangunan      unfurnished
3    3500 mah       bagus sekali  shm - sertifikat hak milik      unfurnished
4    3500 mah              bagus  shm - sertifikat hak milik      unfurnished
5    3500 mah              bagus  shm - sertifikat hak milik   semi furnished
6    4400 mah    Tidak diketahui     hgb - hak guna bangunan  Tidak diketahui
7    3500 mah    Tidak diketahui     hgb - hak guna bangunan  Tidak diketahui
8    4400 mah    Tidak diketahui  shm - sertifikat hak milik   semi furnished
9    3500 mah    Tidak diketahui  shm - sertifikat hak milik   semi furnished

In [39]:
modus_A = df_nonum['electricity'].mode()[0]
df_nonum.replace('lainnya mah', modus_A, inplace=True)

<ipython-input-39-bbb3262c21c7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nonum.replace('lainnya mah', modus_A, inplace=True)

In [40]:
df_nonum['electricity'] = pd.to_numeric(df_nonum['electricity'].str.replace(' mah', ''))

<ipython-input-40-d1ec405b323c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nonum['electricity'] = pd.to_numeric(df_nonum['electricity'].str.replace(' mah', ''))

In [42]:
df_nonum = pd.get_dummies(df_nonum)

In [43]:
df_nonum

,electricity,property_condition_Tidak diketahui,property_condition_bagus,property_condition_bagus sekali,property_condition_baru,property_condition_butuh renovasi,property_condition_semi furnished,property_condition_sudah renovasi,property_condition_unfurnished,certificate_Tidak diketahui,certificate_hgb - hak guna bangunan,certificate_hp - hak pakai,"certificate_lainnya (ppjb,girik,adat,dll)",certificate_shm - sertifikat hak milik,furnishing_Tidak diketahui,furnishing_baru,furnishing_furnished,furnishing_semi furnished,furnishing_unfurnished
0,4400,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,2200,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,2200,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
3,3500,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,3500,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,1300,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0
3549,1300,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3550,1300,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3551,2200,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0
3552,1300,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [46]:
df_baru = df_baru.drop(['price_in_rp','facilities','electricity','property_condition','certificate','furnishing'], axis=1)
# Menggabungkan dataframe
df_merged = pd.merge(pd.merge(df_baru, df_fasil, left_index=True, right_index=True), df_nonum, left_index=True, right_index=True)

In [47]:
df_merged.head(5)

,url,title,address,district,city,lat,long,bedrooms,bathrooms,land_size_m2,...,certificate_Tidak diketahui,certificate_hgb - hak guna bangunan,certificate_hp - hak pakai,"certificate_lainnya (ppjb,girik,adat,dll)",certificate_shm - sertifikat hak milik,furnishing_Tidak diketahui,furnishing_baru,furnishing_furnished,furnishing_semi furnished,furnishing_unfurnished
0,https://www.rumah123.com/properti/bekasi/hos11...,Rumah cantik Sumarecon Bekasi\nLingkungan asri...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,4.0,4.0,239.0,...,0,0,0,0,1,0,0,0,0,1
1,https://www.rumah123.com/properti/bekasi/hos10...,"Rumah Kekinian, Magenta Summarecon Bekasi","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,3.0,2.0,55.0,...,0,1,0,0,0,1,0,0,0,0
2,https://www.rumah123.com/properti/bekasi/hos10...,Rumah Cantik 2 Lantai Cluster Bluebell Summare...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,3.0,3.0,119.0,...,0,1,0,0,0,0,0,0,0,1
3,https://www.rumah123.com/properti/bekasi/hos10...,Rumah Mewah 2Lantai L10x18 C di Cluster VERNON...,"Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,3.0,3.0,180.0,...,0,0,0,0,1,0,0,0,0,1
4,https://www.rumah123.com/properti/bekasi/hos10...,"Rumah Hoek di Cluster Maple Summarecon Bekasi,...","Summarecon Bekasi, Bekasi",Summarecon Bekasi,Bekasi,-6.223945,106.986275,4.0,3.0,328.0,...,0,0,0,0,1,0,0,0,0,1

In [53]:
df_merged.to_csv('FEATURE_ENGINERING.csv', index= False)